// Portfolio projects dataset
export const PROJECTS_DATA = [
  {
    id: 1,
    title: "Task Flow — Management System",
    category: "fullstack",
    tag: "Full Stack PERN App",
    desc: "A comprehensive work-tracking system allowing multi-level task allocation, dynamic priority statuses, and user workload distribution with real-time updates.",
    tech: ["React.js", "Node.js", "Express.js", "PostgreSQL", "REST API"],
    bullets: [
      "Engineered responsive user interface layouts with React.js.",
      "Built scalable backend REST API endpoints using Node.js and Express.js.",
      "Designed and queried normalized relational schemas inside PostgreSQL for persistence.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "https://mmdsameerali-taskflow.netlify.app",
  },
  {
    id: 2,
    title: "CodeBooks — Full Stack Reference",
    category: "frontend",
    tag: "React E-Book & Documentation",
    desc: "An interactive coding reference platform documenting essentials across HTML, CSS, JavaScript, React, Node.js, Express, PostgreSQL, and REST APIs.",
    tech: ["React.js", "JavaScript (ES6+)", "CSS3", "Technical Docs"],
    bullets: [
      "Structured component-based documentation chapters with rapid topic navigation.",
      "Implemented unidirectional state flow for chapter tracking and interactive layout view.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "https://mmdsameerali-codebooks.netlify.app",
  },
  {
    id: 3,
    title: "Typing Master",
    category: "frontend",
    tag: "React State & Speed App",
    desc: "A real-time typing speed and accuracy evaluator built with React, tracking WPM (Words Per Minute), accuracy percentages, and real-time keystroke diagnostics.",
    tech: ["React.js", "React Hooks", "JavaScript (ES6+)", "CSS3"],
    bullets: [
      "Implemented real-time character matching logic and dynamic speed metric calculations.",
      "Managed timer intervals and input state updates without blocking UI rendering.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "#",
  },
  {
    id: 4,
    title: "Currency Converter",
    category: "frontend",
    tag: "Frontend API Application",
    desc: "A dynamic currency conversion tool providing real-time exchange rates calculated directly against live global market values.",
    tech: ["JavaScript", "Fetch API", "Open ER-API", "CSS3 Flexbox"],
    bullets: [
      "Integrated Open ER-API (https://open.er-api.com/v6/latest/) for daily updated market rates.",
      "Handled asynchronous data fetching, dynamic currency pair computations, and real-time DOM updates.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "#",
  },
  {
    id: 5,
    title: "Tic Tac Toe",
    category: "frontend",
    tag: "Interactive Vanilla JS Game",
    desc: "A classic 2-player interactive game implemented using Vanilla JavaScript, HTML5, and CSS3, featuring win-condition detection, draw checks, and reset functionality.",
    tech: ["JavaScript", "DOM Manipulation", "HTML5", "CSS3 Grid"],
    bullets: [
      "Engineered win-checking algorithms across all row, column, and diagonal matrix combinations.",
      "Designed a clean, responsive board layout with instant state reset controls.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "#",
  },
  {
    id: 6,
    title: "E-Commerce Platform",
    category: "fullstack",
    tag: "Full Stack PERN [In Progress]",
    desc: "An end-to-end full-stack digital storefront featuring product catalogs, cart state management, checkout flows, and relational inventory storage.",
    tech: ["React.js", "Node.js", "Express.js", "PostgreSQL", "REST API"],
    bullets: [
      "Developing responsive product browsing, category filtering, and shopping cart modules.",
      "Building scalable backend endpoints for authentication, order processing, and product schemas.",
    ],
    githubUrl: "https://github.com/mmdsameerali",
    liveUrl: "#",
  },
];